name: Update daily data from Bovespa Stock Exchange
on:
  schedule:
    - cron:  '0 8 * * 2-6'
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: bovespa
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.1'
      - name: Process data
        # the script updatedata.sh is inside of the branch
        run: bash .github/workflows/updatedata.sh "${{ secrets.GH_TOKEN }}" "${{ secrets.NAME }}" "${{ secrets.USER_NAME }}" "${{ github.repository }}"