name: Execute Analysis Bovespa
on:
  repository_dispatch:
    types: [start-analysis-bovespa]
jobs:
  callAnalysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: bovespa
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.1'
      - name: Start Analysis
        run: sh .github/workflows/executeAnalysis.sh ${{ github.event.client_payload.file }} ${{ secrets.GH_TOKEN }}
